Beta
OndraGejdos/OG-star-tracker- pull request #28
Opened 2024-12-01 22:14 UTC by chemistorge

Refactored code

Implemented new intervalometer

2024-12-04 20:17 UTC, Sylensky commented
So i put my hands on testing the code as far as i could without hardware and i have couple remarks that might be worth to discuss them.

Firstly what is the advantage of using `pioarduino` fork over the upstream `platform-espressif32`?

Secondly the most noticeable thing is the line endings not being `NL` and something else. If you are using vs code i would check the line endings in the toolbar of the IDE. Aside from that once this pull gets through i will introduce something that keeps the project clean.

2024-12-04 20:33 UTC, Sylensky reviewed
With these changes the code compiles without warnings.

2024-12-04 20:33 UTC, Sylensky commented on esp32_wireless_control/firmware/intervalometer.cpp
> +          ra_axis.counterActive = ra_axis.goToTarget = true;
same as above

2024-12-04 20:33 UTC, Sylensky commented on esp32_wireless_control/firmware/intervalometer.cpp
> +        ra_axis.counterActive = ra_axis.goToTarget = false;
Same as above.

2024-12-04 20:33 UTC, Sylensky commented on esp32_wireless_control/firmware/intervalometer.cpp
> +            ra_axis.goToTarget = ra_axis.counterActive = true;
instead of
```cpp
ra_axis.counterActive = ra_axis.goToTarget = true;
```

do this:
```cpp
ra_axis.counterActive = true;
ra_axis.goToTarget = true;
```

2024-12-04 20:33 UTC, Sylensky commented on esp32_wireless_control/firmware/firmware.ino
> +        break;
Missing case and default in the switch that fixes compiler warning:
```cpp
      case Intervalometer::INACTIVE:
      default:
        break;
````

2024-12-04 20:33 UTC, Sylensky commented on esp32_wireless_control/firmware/firmware.ino
> +      default:
The `captureMode` might be used initialized. Define a default mode where no action is happening like:
```cpp
      default:
        captureMode = Intervalometer::NO_ACTION_MODE
```

2024-12-04 21:09 UTC, Sylensky requested changes

2024-12-04 21:09 UTC, Sylensky commented on esp32_wireless_control/firmware/axis.cpp
> +    ra_axis.axisAbsoluteDirection ? ra_axis.axisCountValue++ : ra_axis.axisCountValue--;
'++' expression of 'volatile'-qualified type is deprecated and should be avoided. Use simpler code like:
```cpp
    int temp = ra_axis.axisCountValue;
    ra_axis.axisAbsoluteDirection ? temp++ : temp--;
    ra_axis.axisCountValue = temp;
```

2024-12-04 21:09 UTC, Sylensky commented on esp32_wireless_control/firmware/axis.cpp
> +    dec_axis.axisAbsoluteDirection ? dec_axis.axisCountValue++ : dec_axis.axisCountValue--;
Similiar thing applies here.

2024-12-04 21:09 UTC, Sylensky commented on esp32_wireless_control/firmware/axis.cpp
> +  trackingDirection = axisAbsoluteDirection = directionArg;
Missed a compiler warning here:
```cpp

  trackingDirection = directionArg;
  axisAbsoluteDirection = directionArg;
```

2024-12-04 22:23 UTC, Sylensky commented on esp32_wireless_control/README.md
>   -- AP  : The ESP32 will create a wifi network which you can connect to
Squash the update readme commits into one single update readme commit.

2024-12-06 14:09 UTC, chemistorge commented on esp32_wireless_control/firmware/firmware.ino
> +      default:
Hi, Not sure what you mean here. Why a no action mode? As capture is only started with a valid mode 0-3.

2024-12-06 14:10 UTC, chemistorge commented on esp32_wireless_control/firmware/intervalometer.cpp
> +          ra_axis.counterActive = ra_axis.goToTarget = true;
Fixed

2024-12-06 14:10 UTC, chemistorge commented on esp32_wireless_control/firmware/intervalometer.cpp
> +        ra_axis.counterActive = ra_axis.goToTarget = false;
fixed

2024-12-06 14:11 UTC, chemistorge commented on esp32_wireless_control/firmware/intervalometer.cpp
> +            ra_axis.goToTarget = ra_axis.counterActive = true;
fixed

2024-12-06 14:11 UTC, chemistorge commented on esp32_wireless_control/firmware/axis.cpp
> +    ra_axis.axisAbsoluteDirection ? ra_axis.axisCountValue++ : ra_axis.axisCountValue--;
fixed

2024-12-06 14:12 UTC, chemistorge commented on esp32_wireless_control/firmware/axis.cpp
> +    dec_axis.axisAbsoluteDirection ? dec_axis.axisCountValue++ : dec_axis.axisCountValue--;
fixed

2024-12-06 14:13 UTC, chemistorge commented on esp32_wireless_control/firmware/axis.cpp
> +  trackingDirection = axisAbsoluteDirection = directionArg;
fixed

2024-12-06 14:34 UTC, chemistorge commented
> So i put my hands on testing the code as far as i could without hardware and i have couple remarks that might be worth to discuss them.
> 
> Firstly what is the advantage of using `pioarduino` fork over the upstream `platform-espressif32`?
> 
> ~Secondly the most noticeable thing is the line endings not being `NL` and something else. If you are using vs code i would check the line endings in the toolbar of the IDE. Aside from that once this pull gets through i will introduce something that keeps the project clean.~ Seems like this was an issue with my vs code that behaved wierd.

I think my platformio must have been out of date as my version of expressif32 would not work with the new timer api that is in arduino-esp32 v3.0.x. I have changed back to expressif32

2024-12-06 14:36 UTC, chemistorge commented on esp32_wireless_control/firmware/firmware.ino
> +        break;
Fixed

2024-12-06 15:12 UTC, chemistorge commented on esp32_wireless_control/README.md
>   -- AP  : The ESP32 will create a wifi network which you can connect to
Done

2024-12-06 15:54 UTC, Sylensky commented
> > So i put my hands on testing the code as far as i could without hardware and i have couple remarks that might be worth to discuss them.
> > 
> > Firstly what is the advantage of using `pioarduino` fork over the upstream `platform-espressif32`?
> > 
> > ~Secondly the most noticeable thing is the line endings not being `NL` and something else. If you are using vs code i would check the line endings in the toolbar of the IDE. Aside from that once this pull gets through i will introduce something that keeps the project clean.~ Seems like this was an issue with my vs code that behaved wierd.
> 
> I think my platformio must have been out of date as my version of expressif32 would not work with the new timer api that is in arduino-esp32 v3.0.x. I have changed back to expressif32

Maybe locking the version of the v3.0.x would be nice since the arduinojson is locked aswell.

2024-12-06 15:59 UTC, Sylensky commented
I would create fixup commits addressing the individual changes and rebasing them instead.

2024-12-06 16:19 UTC, chemistorge commented
> I would create fixup commits addressing the individual changes and rebasing them instead.

I am not that familiar with git, how does that work?

2024-12-06 21:05 UTC, Sylensky commented
> > I would create fixup commits addressing the individual changes and rebasing them instead.
> 
> I am not that familiar with git, how does that work?

What it does is creating a fix commit that references the commit that introduced the faulty code. It is super useful to keep the commit history clean and tidy.

In a nutshell you do make your desired changes and `git add -p` (for interactive selection of the individual change) to staging which is then used to create the fixup commit with `git commit --fixup=<original commit hash that needs the fix>`.
That generates the same commit message with a `!fixup:` prefix. That commit can be merged together in  the interactive rebase or with autosquash. (i do prefer the manual interactive rebase for the extra level of control)
Quite some tutorials can be found out there, for example this one: https://fle.github.io/git-tip-keep-your-branch-clean-with-fixup-and-autosquash.html

2024-12-06 21:37 UTC, chemistorge commented
> > > I would create fixup commits addressing the individual changes and rebasing them instead.
> > 
> > 
> > I am not that familiar with git, how does that work?
> 
> What it does is creating a fix commit that references the commit that introduced the faulty code. It is super useful to keep the commit history clean and tidy.
> 
> In a nutshell you do make your desired changes and `git add -p` (for interactive selection of the individual change) to staging which is then used to create the fixup commit with `git commit --fixup=<original commit hash that needs the fix>`. That generates the same commit message with a `!fixup:` prefix. That commit can be merged together in the interactive rebase or with autosquash. (i do prefer the manual interactive rebase for the extra level of control) Quite some tutorials can be found out there, for example this one: https://fle.github.io/git-tip-keep-your-branch-clean-with-fixup-and-autosquash.html

Tried to do that but it is in my alpha branch. Not the beta and the pull request from alpha to beta is not changed. My alpha branch now has three sub branches and is a bit of a mess of commits.

2024-12-06 21:59 UTC, Sylensky commented
> > What it does is creating a fix commit that references the commit that introduced the faulty code. It is super useful to keep the commit history clean and tidy.
> > In a nutshell you do make your desired changes and `git add -p` (for interactive selection of the individual change) to staging which is then used to create the fixup commit with `git commit --fixup=<original commit hash that needs the fix>`. That generates the same commit message with a `!fixup:` prefix. That commit can be merged together in the interactive rebase or with autosquash. (i do prefer the manual interactive rebase for the extra level of control) Quite some tutorials can be found out there, for example this one: https://fle.github.io/git-tip-keep-your-branch-clean-with-fixup-and-autosquash.html
> 
> Tried to do that but it is in my alpha branch. Not the beta and the pull request from alpha to beta is not changed. My alpha branch now has three sub branches and is a bit of a mess of commits.

It gets easier the more you fiddle with it. I can assist you and in terms of a walkthrough on your branches.

For now this looks good to me. Allthough  large PR's tend to be less transparent to the reader and whats going on but refactoring bear the potential for lots of chagnes so this one looks fine.

Now it would be great to be able to close discussions permission-wise or maybe on of @OndraGejdos or @Th0MmyS could do so.

2024-12-08 19:50 UTC, chemistorge commented
I will have a look at the tutorial on fix up. My Alpha branch is now redundant as it has all been pulled to the beta branch.  Hopefully this can now be pulled.

2024-12-20 15:16 UTC, chemistorge commented
Add web language support to this pull request which resolves conflicts with pull #34 and replaces it.

2024-12-21 07:33 UTC, Sylensky commented
I would atleast honor the original creator of the multi language support by adding his signature to the commit 8b678cffe737c724bac4033531a70ec900e15134.

You can add in a first step your signature with `git commit --ammend --no-edit -s` and then change the signature of yours with the one from the original commit interactively with `git commit --ammend`.

2024-12-21 12:05 UTC, chemistorge commented
With the git commit --what do I edit to add signature of original creator? 

Merge pull request #2 from chemistorge/alpha_lang

Web language change now added to this pull request

Signed-off-by: chemistorge <chemistorge@googlemail.com>

# Please enter the commit message for your changes. Lines starting
# with '#' will be ignored, and an empty message aborts the commit.
#
# Author:    chemistorge <90050093+chemistorge@users.noreply.github.com>
# Date:      Fri Dec 20 15:07:55 2024 +0000
#
# On branch beta
# Your branch and 'origin/beta' have diverged,
# and have 1 and 1 different commits each, respectively.
#
# Changes to be committed:
#       new file:   esp32_wireless_control/firmware/chineseLanguage.h
#       modified:   esp32_wireless_control/firmware/config.h
#       new file:   esp32_wireless_control/firmware/englishLanguage.h
#       modified:   esp32_wireless_control/firmware/firmware.ino
#       modified:   esp32_wireless_control/firmware/hardwaretimer.h
#       modified:   esp32_wireless_control/firmware/index_html.h
#       new file:   esp32_wireless_control/firmware/nextLanguage.h
#       new file:   esp32_wireless_control/firmware/web_languages.cpp
#       new file:   esp32_wireless_control/firmware/web_languages.h
#       modified:   esp32_wireless_control/firmware/website_strings.cpp
#       modified:   esp32_wireless_control/firmware/website_strings.h
#

2024-12-21 12:08 UTC, chemistorge commented
Is it the sign off bit?

2024-12-21 12:17 UTC, chemistorge commented
Or the Author bit

2024-12-22 08:58 UTC, Sylensky commented
You change the `signed-of-by` entry to his username and the email he used.

2024-12-22 10:10 UTC, chemistorge commented
> You change the `signed-of-by` entry to his username and the email he used.

Did that and saved it then I had to pull and rebase. Not getting on with git.

Has it worked? As when I look at the message it has no signed-of-by anymore?

2024-12-22 10:22 UTC, chemistorge commented
> > You change the `signed-of-by` entry to his username and the email he used.
> 
> Did that and saved it then I had to pull and rebase. Not getting on with git.
> 
> Has it worked? As when I look at the message it has no signed-of-by anymore?

Redone and did a force push instead of rebase and it is now showing correct sign off

2024-12-22 16:41 UTC, Sylensky commented
> > > You change the `signed-of-by` entry to his username and the email he used.
> > 
> > Did that and saved it then I had to pull and rebase. Not getting on with git.
> > 
> > Has it worked? As when I look at the message it has no signed-of-by anymore?
> 
> Redone and did a force push instead of rebase and it is now showing correct sign off

Looks good to me. Lets get this merged!

2024-12-24 20:09 UTC, merged

2024-12-24 20:09 UTC, Th0MmyS commented
Roger that, merging