Add multi-language switching function in web interface
OndraGejdos/OG-star-tracker- pull request #33
Opened 2024-12-05 16:55 UTC by Th0MmyS

2024-12-05 21:02 UTC, Sylensky requested changes

2024-12-05 21:02 UTC, Sylensky commented on esp32_wireless_control/firmware/firmware.ino
> +// 添加当前语言变量
Keep comments in plain english.

2024-12-05 21:02 UTC, Sylensky commented on esp32_wireless_control/firmware/firmware.ino
> +    int tracking_speed = server.arg(getParamKey(STR_TRACKING_SPEED)).toInt();
This change should not belong to the commit introducing the language switch support. Create a seperate commit with corresponding description.

2024-12-05 21:02 UTC, Sylensky commented on esp32_wireless_control/firmware/firmware.ino
> +    if (!s_slew_active) {  //if slew is not active - needed for ipad (passes multiple touchon events)
Do not format the code in the same commit. -> seperate formatting commit.

2024-12-05 21:02 UTC, Sylensky commented on esp32_wireless_control/firmware/firmware.ino
> +        char status[60];
Only change the necessary lines for the language support.

2024-12-05 21:02 UTC, Sylensky commented on esp32_wireless_control/firmware/firmware.ino
> +}
Missing newline at end of file.

2024-12-05 21:02 UTC, Sylensky commented on esp32_wireless_control/firmware/template.cpp
> +}
missing newline at end of file.

2024-12-05 21:02 UTC, Sylensky commented on esp32_wireless_control/firmware/template.h
> +#endif
Missing newline at end of file.

2024-12-05 21:05 UTC, Sylensky commented
@YihuiLu your PR contains good code related to the website and the string handling. Just some minor things that should be refactored to keep the codebase consistent.
Please review and update your branch here accordingly.

2024-12-05 21:25 UTC, Sylensky requested changes
The timer feature causes lots of problems when trying to compile the project. Can you compile it on your side again and verify that?

2024-12-05 21:25 UTC, Sylensky commented on esp32_wireless_control/firmware/strings.h
> +String getHTML();
This should be `std::string getHTML()` otherwise it does not compile. The change should be reflected in the corresponding cpp file aswell.

That also requires `#include <string>` on top of the includes.

2024-12-05 21:25 UTC, Sylensky commented on esp32_wireless_control/firmware/strings.h
> +    static String build(const char* tmpl, Language lang);
Same for this.

2024-12-05 21:25 UTC, Sylensky commented on esp32_wireless_control/firmware/strings.h
> +    static void replaceAll(String& html, Language lang);
+1

2024-12-06 22:01 UTC, Sylensky commented
This PR can be closed in favor of #34.

2024-12-07 07:57 UTC, YihuiLu commented
Now I can't close this pull request, please help me close it Thank you
@Th0MmyS

2024-12-21 07:24 UTC, closed without merging