Added the function of switching the language of the web page
OndraGejdos/OG-star-tracker- pull request #34
Opened 2024-12-06 08:47 UTC by YihuiLu

This is a duplicate commit, see https://github.com/OndraGejdos/OG-star-tracker-/pull/33
The last mentioned issue has been fixed, and I can compile normally:
Dependencies used: https://github.com/espressif/arduino-esp32/releases/tag/2.0.17
I compiled using ArduinoIDE

## Implement the following functions:
1. Switch languages at the top of the page
2. After the switch, this personalization is stored in the user's cookie, and the next launch of the page will still be in the user's selected language
3. If the page is not localized for a language, English will be displayed by default
4. The code structure is convenient for the sinicization of other languages

## The changes are as follows:
1. Rewritten the page keyword mapping logic
2. Added a language switch button at the top of the page
3. Modified the page text replacement code logic

## As a result, the following parts had to be adjusted:
1. Modify the handleRoot function
2. Most of the routing functions get the return value method modifications, such as:
```c++
direction = server.arg(DIRECTION).toInt(); 
```
Modified to:
```c++
direction = server.arg(getParamKey(STR_DIRECTION)).toInt();
```
This is a must, and the rest of the logic remains unchanged

4. Added two template files
5. Individual code styles have changed slightly due to the editor's auto-formatting feature
6. html template file format optimization

2024-12-06 08:56 UTC, Sylensky requested changes
Its a lot better then before but still contains some confusion.

2024-12-06 08:56 UTC, Sylensky commented on esp32_wireless_control/firmware/config.h
>  #define MS2           22
I think this commit should not be necessary when you rebase your branch to the `upstream/beta` branch.

2024-12-06 08:56 UTC, Sylensky commented on esp32_wireless_control/firmware/firmware.ino
>        .replaceSelected("north", direction == 1)
Squash this commit into the 616e8e1e40ea765ff14bf7a143a8d13c96a662bf commit.

2024-12-06 08:58 UTC, Sylensky commented
Can you try to to buld it with https://github.com/espressif/arduino-esp32/releases/tag/3.0.7 aswell? There might be some incompatibilities that will arise as soon as the other pull requests will be merged.

2024-12-06 09:05 UTC, YihuiLu commented
Okay, currently I cannot compile using 3.x.x. In fact, I have never successfully compiled using 3.x.x dependencies. This should be a legacy issue and has nothing to do with this modification.

2024-12-06 09:14 UTC, YihuiLu commented on esp32_wireless_control/firmware/firmware.ino
>        .replaceSelected("north", direction == 1)
Merge all of this commit into 616e8e1? Please confirm

2024-12-06 09:37 UTC, YihuiLu commented on esp32_wireless_control/firmware/config.h
>  #define MS2           22
After checking it out, it came to the conclusion that my editor thought that the line of code was mixed with tabs in the spaces, so it was modified, and I thought it could be committed

2024-12-06 09:54 UTC, YihuiLu commented on esp32_wireless_control/firmware/firmware.ino
>        .replaceSelected("north", direction == 1)
![112211](https://github.com/user-attachments/assets/2bc7ada5-b0ce-4606-b439-9c4b2b2113c6)
Since I did something unexpected that prevented me from squashing the given commits, I tried to squash the other commits but it looked more confusing. If it doesn't cause a bigger problem, can it be merged directly? I'll pay attention to the commit strategy and all the details the next time I commit code

2024-12-06 10:09 UTC, YihuiLu commented
If a 3.x.x dependency can be used, the merge can be postponed. Or you can enable a new branch to be compatible with 3.x.x

2024-12-09 01:26 UTC, Sylensky commented on esp32_wireless_control/firmware/firmware.ino
>        .replaceSelected("north", direction == 1)
I put my hand on it and it quickly escalated in a conflict frenzy. I presume it is better for now to just go forward and keep it in mind for future pull requests.

2024-12-09 01:30 UTC, Sylensky commented
> If a 3.x.x dependency can be used, the merge can be postponed. Or you can enable a new branch to be compatible with 3.x.x

I think the beta PR will have a look based on the changes introduces here. @chemistorge Would you mind spare an eye on the required changes to be compatible with your beta branch? Maybe we should push this PR through and clean up afterwards?

2024-12-10 11:41 UTC, chemistorge commented
Hi, Can you let me know what needs to be done, As I can see the other Pull
request are based off the old code. Do you want me to look at the other
Pull requests?

On Mon, 9 Dec 2024, 01:31 Sylensky, ***@***.***> wrote:

> If a 3.x.x dependency can be used, the merge can be postponed. Or you can
> enable a new branch to be compatible with 3.x.x
>
> I think the beta PR will have a look based on the changes introduces here.
> @chemistorge <https://github.com/chemistorge> Would you mind spare an eye
> on the required changes to be compatible with your beta branch? Maybe we
> should push this PR through and clean up afterwards?
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/OndraGejdos/OG-star-tracker-/pull/34#issuecomment-2526596538>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AVPA4LKHS35QXEXPWU3CRID2ETXGFAVCNFSM6AAAAABTEGPCUSVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMZDKMRWGU4TMNJTHA>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2024-12-10 11:45 UTC, chemistorge commented
> Okay, currently I cannot compile using 3.x.x. In fact, I have never successfully compiled using 3.x.x dependencies. This should be a legacy issue and has nothing to do with this modification.

The changes fro V2.x to V3.x are the timer API (v3.x simplifies the timer functions) also using string.h  as a file name conflicts with the v3 build. also the string name "html" is taken. In my new pull request I have moved over to V3.0 as arduino IDE now defaults to this and it made implementing the timer code simpler and easier for future development.

2024-12-10 16:30 UTC, chemistorge commented
Thank you @YihuiLu  for the translations into Chinese. 

I have had a look at this Pull request: I can reformat these changes into my beta request. 
The way the language change is implemented requests a for loop iteration for each replace look up. This is not scalable to multiple languages as the more languages the longer the iteration is going to take. I would suggest a string array for each language and pass a pointer to the correct language array to handle language function. As a enum with all keys has been created   (enum StringID )  this be used as the index into the correct language array to retrieve strings, removing all for loop iterations.

going forward a new language can be added by just providing a string array and adding the option to web page and handle language function. 

I can implement this if you would like.

2024-12-10 20:48 UTC, Sylensky commented
> Thank you @YihuiLu for the translations into Chinese.
> 
> I have had a look at this Pull request: I can reformat these changes into my beta request. The way the language change is implemented requests a for loop iteration for each replace look up. This is not scalable to multiple languages as the more languages the longer the iteration is going to take. I would suggest a string array for each language and pass a pointer to the correct language array to handle language function. As a enum with all keys has been created (enum StringID ) this be used as the index into the correct language array to retrieve strings, removing all for loop iterations.
> 
> going forward a new language can be added by just providing a string array and adding the option to web page and handle language function.
> 
> An array of pointers to the language arrays can be created and use the language enum as the index
> 
> As my pull request implement a new intervalometer, additional translations will be needed.
> 
> I can implement this if you would like.

With that you pretty much answered what i requested. You mentioned the required changes from v2 -> v3 and found an additional functional change to the language translation i haven't seen yet.

From the pull request order i presume this should get merged first. followed by the rest of the PRs.

2024-12-11 10:25 UTC, chemistorge commented
> > Thank you @YihuiLu for the translations into Chinese.
> > I have had a look at this Pull request: I can reformat these changes into my beta request. The way the language change is implemented requests a for loop iteration for each replace look up. This is not scalable to multiple languages as the more languages the longer the iteration is going to take. I would suggest a string array for each language and pass a pointer to the correct language array to handle language function. As a enum with all keys has been created (enum StringID ) this be used as the index into the correct language array to retrieve strings, removing all for loop iterations.
> > going forward a new language can be added by just providing a string array and adding the option to web page and handle language function.
> > An array of pointers to the language arrays can be created and use the language enum as the index
> > As my pull request implement a new intervalometer, additional translations will be needed.
> > I can implement this if you would like.
> 
> With that you pretty much answered what i requested. You mentioned the required changes from v2 -> v3 and found an additional functional change to the language translation i haven't seen yet.

Which functional change?

> 
> From the pull request order i presume this should get merged first. followed by the rest of the PRs.

Is my beta going to be pulled first, this will allow others to update there pull request as there are many changes from previous version. Request #34 will have too many conflicts with my beta and will need many additions.

2024-12-11 11:23 UTC, Sylensky commented
With functional changes i meant the timer api changes.


Hm right and considering that this still requests changes it is a better idea to merge the beta branch first.
But it needs now attention from @Th0MmyS or @OndraGejdos to decide which should get merged.

2024-12-21 06:14 UTC, YihuiLu commented
> Thank you @YihuiLu for the translations into Chinese.
> 
> I have had a look at this Pull request: I can reformat these changes into my beta request. The way the language change is implemented requests a for loop iteration for each replace look up. This is not scalable to multiple languages as the more languages the longer the iteration is going to take. I would suggest a string array for each language and pass a pointer to the correct language array to handle language function. As a enum with all keys has been created (enum StringID ) this be used as the index into the correct language array to retrieve strings, removing all for loop iterations.
> 
> going forward a new language can be added by just providing a string array and adding the option to web page and handle language function.
> 
> An array of pointers to the language arrays can be created and use the language enum as the index
> 
> As my pull request implement a new intervalometer, additional translations will be needed.
> 
> I can implement this if you would like.

Thank you, I agree with your idea, please help me to make this idea a reality. I'm currently slow to process this merge request due to busy work, you can speed it up

2024-12-21 06:16 UTC, YihuiLu commented
Also can anyone help me close this merge request, it should have been deprecated :https://github.com/OndraGejdos/OG-star-tracker-/pull/33 @Sylensky @Th0MmyS @chemistorge

2024-12-24 20:17 UTC, closed without merging

2024-12-24 20:17 UTC, Th0MmyS commented
done :)